### ISSUE TITLE
Issue 1 - User can convert currencies.

### ISSUE THREAD

**Issue by NangKTu** [NangKTu/Dollars-to-Euros#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose base currency and convert it to currency of their choosing. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users choose currency from a list and pull data from api. 

## 🖼️ Wireframes

N/A

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create html header for the page with 3 containers(home icon, page title, eye icon) distribute evenly in a row. 
- [x] Below header, create 2 containers with 2 divs inside(currency, currency rate).
- [x] Complete html with appropriate responsive layout classes.
   - [x] Write CSS codes for mobile first.
   - [x] Write codes to adjust to desktop.
- [x] Write function to get XMLHttpRequest from api to populate currency rate
- [x] Test the feature and clean up
